

default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: knights_apprentices_app_development

  
test:
  <<: *default
  database: knights_apprentices_app_test


production:
  <<: *default
  database: knights_apprentices_app_production
  username: knights_apprentices_app
  password: <%= ENV["KNIGHTS_APPRENTICES_APP_DATABASE_PASSWORD"] %>
